//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webEjemplo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCursos
    {
        public int idCurso { get; set; }
        public string sigla { get; set; }
        public string nombre { get; set; }
        public string lugar { get; set; }
        public string ciclo { get; set; }
        public int creditos { get; set; }
        public byte[] programa { get; set; }
        public string estado { get; set; }
        public int totalHoras { get; set; }
        public string modalidad { get; set; }
        public string nombrePrograma { get; set; }
    }
}
